# Generated by Django 4.2.4 on 2023-09-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='appoinment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labaratory_test', to='events.appointment'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labaratory_test', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labaratory_test', to='hospital.patient'),
        ),
    ]
