# Generated by Django 4.2.4 on 2023-09-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_rename_amdission_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='residual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partly_paid', 'Partly paid'), ('paid', 'Paid')], default='pending', max_length=11),
        ),
    ]
