# Generated by Django 4.2.4 on 2023-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary_currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('uzs', 'UZS')], default='usd', max_length=3),
        ),
    ]
